chore: add sandbox iframe
TypedProject/vuepress-theme-tsed pull request #82
Opened 2020-11-11 17:28 UTC by nicomartin92

2020-11-11 18:11 UTC, Romakita requested changes

2020-11-11 18:11 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
Ha voué tiens tu ne fais l'iframe dans le template du coup ?

2020-11-11 18:11 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe.setAttribute('style', `width:80%; height:500px; margin: 0 auto; border:0; border-radius: 4px; overflow:hidden; font-size: ${this.fontSize}px`);
je serais plutot d'avis de faire en sorte que le style soit celui du parent ou à defaut qu'on le passe par props.

2020-11-11 18:11 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
C'etait pas plus simple de le mettre comme ça:

```
<template>
<iframe :title="title"  />
</template>
```

2020-11-11 18:11 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      if (this.sandboxId) this.iframe.setAttribute('sandbox-id', this.sandboxId);
Du coup je suis pas certain que ça marche :)

Si tu prends l'exemple de la storie l'iframe à générer est la suivante:

```typescript
<iframe src="https://codesandbox.io/embed/laughing-kepler-ripfl?fontsize=14&hidenavigation=1&theme=dark"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="tsed-swagger-example"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"></iframe>
```

Par exemple `src `est la concaténation des éléments suivants: `'https://codesandbox.io/embed/' + sandboxId + '?fontsize=' + fontSize + '&hidenavigation=' + (hideNavigation ? 1 : 0) +  '&theme='+theme `

2020-11-12 18:43 UTC, nicomartin92 commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
Heu si c'est mieux je vais changer ça :)

2020-11-12 19:37 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
Ba en fait je te pose la question :)

2020-11-12 19:38 UTC, Romakita commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
J’imagine que le mounted est pour eviter le rendering multiple.

2020-11-18 08:53 UTC, Romakita commented
@nicomartin92 Est-ce que tu as besoin de plus d'info sur le besoin ?

2020-11-18 18:17 UTC, nicomartin92 commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      this.iframe = document.createElement('iframe');
Le passer via l'iframe directement marche aussi.

2020-11-18 18:34 UTC, nicomartin92 commented on packages/vuepress-common/src/components/molecules/code-sandbox/CodeSandbox.vue
> +      if (this.sandboxId) this.iframe.setAttribute('sandbox-id', this.sandboxId);
Ah oui bien vu je n'avais pas capté la subtilité.

2020-11-21 07:12 UTC, Romakita approved these changes

2020-11-21 07:12 UTC, merged

2020-11-21 07:17 UTC, Romakita commented
:tada: This PR is included in version 3.5.2 :tada:

The release is available on [GitHub release](https://github.com/TypedProject/vuepress-theme-tsed/releases/tag/v3.5.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: